version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules

  backend:
    image: tiangolo/uvicorn-gunicorn-fastapi
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/mydb
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb

  proxy:
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

volumes:
  node_modules: